repos:
-   repo: https://github.com/hmrc/security-git-hooks
    rev: release/1.11.0
    hooks:
    -   id: secrets_filecontent
        name: Checking staged files for sensitive content
        exclude: ".tar$|.gz$|.jar$|.7z$|.rar$|.bz2$|.zip$|.gzip$|.war$|.ear$|.xlsx$|.xls$|
                |.docx$|.doc$|.pptx$|.pdf$|.jpg$|.png$|.jpeg$|.tif$|.tiff$|.gif$|.bmp$|.webp$|.svg$|.ico$|.psd$|.exe$|.dll$|.dmg$|.de$|.rpm$"
    -   id: hooks_version_check
        name: Checking local hooks against latest release
        verbose: true
